# Generated by Django 4.1 on 2022-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleLearn', models.CharField(max_length=50)),
                ('descriptionLearn', models.CharField(max_length=50)),
                ('postLearn', models.CharField(max_length=500)),
                ('dataLearn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
