# Generated by Django 4.1 on 2022-08-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_learn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learn',
        ),
    ]
